# Generated by Django 5.2.3 on 2025-06-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("subcategory", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("desc", models.CharField(max_length=300)),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
